-- CCT-CN Web 持久化（SQL Server）
-- 在 SSMS 中选中数据库后执行，或使用 sqlcmd

IF DB_ID(N'CCT_CN') IS NULL
BEGIN
  CREATE DATABASE CCT_CN COLLATE Chinese_PRC_CI_AS;
END
GO

USE CCT_CN;
GO

IF OBJECT_ID(N'dbo.ChatMessages', N'U') IS NOT NULL DROP TABLE dbo.ChatMessages;
IF OBJECT_ID(N'dbo.ChatThreads', N'U') IS NOT NULL DROP TABLE dbo.ChatThreads;
IF OBJECT_ID(N'dbo.Components', N'U') IS NOT NULL DROP TABLE dbo.Components;
IF OBJECT_ID(N'dbo.UserBilling', N'U') IS NOT NULL DROP TABLE dbo.UserBilling;
IF OBJECT_ID(N'dbo.UserPreferences', N'U') IS NOT NULL DROP TABLE dbo.UserPreferences;
IF OBJECT_ID(N'dbo.Users', N'U') IS NOT NULL DROP TABLE dbo.Users;
GO

CREATE TABLE dbo.Users (
  Id BIGINT NOT NULL CONSTRAINT PK_Users PRIMARY KEY IDENTITY(1, 1),
  Username NVARCHAR(32) NOT NULL,
  DisplayName NVARCHAR(128) NOT NULL CONSTRAINT DF_Users_Display DEFAULT (N''),
  SaltHex NVARCHAR(512) NOT NULL,
  HashHex NVARCHAR(512) NOT NULL,
  CreatedAt DATETIME2 NOT NULL CONSTRAINT DF_Users_Created DEFAULT (SYSUTCDATETIME()),
  CONSTRAINT UQ_Users_Username UNIQUE (Username)
);

CREATE TABLE dbo.UserPreferences (
  UserId BIGINT NOT NULL CONSTRAINT PK_UserPreferences PRIMARY KEY,
  Theme NVARCHAR(16) NOT NULL CONSTRAINT DF_UserPref_Theme DEFAULT (N'dark'),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_UserPref_Upd DEFAULT (SYSUTCDATETIME()),
  CONSTRAINT FK_UserPref_User FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
);

CREATE TABLE dbo.UserBilling (
  UserId BIGINT NOT NULL CONSTRAINT PK_UserBilling PRIMARY KEY,
  Tier NVARCHAR(16) NOT NULL CONSTRAINT DF_UserBilling_Tier DEFAULT (N'free'),
  TokenQuota BIGINT NOT NULL CONSTRAINT DF_UserBilling_Quota DEFAULT (50000),
  TokensConsumed BIGINT NOT NULL CONSTRAINT DF_UserBilling_Consumed DEFAULT (0),
  PeriodYm INT NOT NULL CONSTRAINT DF_UserBilling_Period DEFAULT (0),
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_UserBilling_Upd DEFAULT (SYSUTCDATETIME()),
  CONSTRAINT FK_UserBilling_User FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
);

CREATE TABLE dbo.Components (
  Id BIGINT NOT NULL CONSTRAINT PK_Components PRIMARY KEY IDENTITY(1, 1),
  UserId BIGINT NOT NULL,
  Kind NVARCHAR(16) NOT NULL,
  Slug NVARCHAR(120) NOT NULL,
  ContentMd NVARCHAR(MAX) NOT NULL,
  UpdatedAt DATETIME2 NOT NULL CONSTRAINT DF_Comp_Upd DEFAULT (SYSUTCDATETIME()),
  CONSTRAINT FK_Comp_User FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE,
  CONSTRAINT UQ_Comp_UserKindSlug UNIQUE (UserId, Kind, Slug)
);

CREATE TABLE dbo.ChatThreads (
  UserId BIGINT NOT NULL,
  ThreadId NVARCHAR(48) NOT NULL,
  Title NVARCHAR(512) NOT NULL,
  Updated BIGINT NOT NULL CONSTRAINT DF_CT_Updated DEFAULT (0),
  Ordinal BIGINT NOT NULL CONSTRAINT DF_CT_Ordinal DEFAULT (0),
  WorkspaceAnchor NVARCHAR(512) NOT NULL CONSTRAINT DF_CT_WorkspaceAnchor DEFAULT (N''),
  CONSTRAINT PK_ChatThreads PRIMARY KEY (UserId, ThreadId),
  CONSTRAINT FK_ChatThreads_User FOREIGN KEY (UserId) REFERENCES dbo.Users (Id) ON DELETE CASCADE
);

CREATE INDEX IX_ChatThreads_User_Ordinal ON dbo.ChatThreads (UserId, Ordinal DESC);

CREATE TABLE dbo.ChatMessages (
  UserId BIGINT NOT NULL,
  ThreadId NVARCHAR(48) NOT NULL,
  Seq INT NOT NULL,
  Role NVARCHAR(16) NOT NULL,
  Content NVARCHAR(MAX) NOT NULL,
  CONSTRAINT PK_ChatMessages PRIMARY KEY (UserId, ThreadId, Seq),
  CONSTRAINT FK_ChatMessages_Threads FOREIGN KEY (UserId, ThreadId) REFERENCES dbo.ChatThreads (UserId, ThreadId) ON DELETE CASCADE
);
GO
